server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /scm
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
  health:
    jms:
      enabled: false

spring:
  # activemq配置
  activemq:
    user: admin
    password: admin
    broker-url:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.163.com
    username: jeecgos@163.com
    password: ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
    initialize-schema: embedded
    #设置自动启动，默认为 true
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 10000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  activiti:
    check-process-definitions: false
    #启用作业执行器
    async-executor-activate: false
    #启用异步执行器
    job-executor-activate: false
  jpa:
    open-in-view: false
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j,showSQL
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url:  jdbc:mysql://172.16.4.219:3306/supplier-chain?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 654321
          driver-class-name: com.mysql.jdbc.Driver
          # 多数据源配置
          #multi-datasource1:
          #url: jdbc:mysql://localhost:3306/jeecg-boot2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          #username: root
          #password: root
          #driver-class-name: com.mysql.cj.jdbc.Driver
  #redis 配置
  redis:
    database: 0
    host: 172.16.4.219
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: yourpassword
    port: 6379
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml,classpath*:com/dongxin/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_UUID
      # 默认数据库表下划线命名
      table-underline: true
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    # 这玩意不好用，用我开发的
    # log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
#jeecg专用配置
jeecg:
  # 本地：local\Minio：minio\阿里云：alioss
  uploadType: fdfs
  path:
    #文件上传根目录 设置
    upload: D://opt//upFiles
    #webapp文件路径
    webapp: D://opt//webapp
  #短信秘钥
  sms:
    accessKeyId: ??
    accessKeySecret: ??
  shiro:
    excludeUrls: /msg/recv/**,/internal0_/**,/test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**,/sm/getActualDelivery/getActualDelivery,/sm/getActualDelivery/getTransferDelivery
    tokenExpired: 7200000
  #阿里云oss存储配置
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: ??
    secretKey: ??
    bucketName: jeecgos
    staticDomain: ??
  # ElasticSearch 6设置
  elasticsearch:
    cluster-name: jeecg-ES
    cluster-nodes: 127.0.0.1:9200
    check-enabled: false
  # 表单设计器配置
  desform:
    # 主题颜色（仅支持 16进制颜色代码）
    theme-color: "#1890ff"
    # 文件、图片上传方式，可选项：qiniu（七牛云）、system（跟随系统配置）
    upload-type: system
  # 在线预览文件服务器地址配置
  file-view-domain: http://172.16.4.194:8012/preview
  # minio文件上传
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: otatest
  #大屏报表参数设置
  jmreport:
    #是否需要校验token
    is_verify_token: false
    #必须校验方法
    verify_methods: remove,delete,save,add,update
  #Wps在线文档
  wps:
    domain: https://wwo.wps.cn/office/
    appid: ??
    appsecret: ??
  fdfs:
    url: http://172.16.3.56
    group: group1
    basePath: scm/dev
    appId: um4KZaVZ
    appSecret: 3c8c1e74c3a005552c473bba1841bbe06cea5475
    authUrl: http://172.16.3.54:8081/token/generate
  ddl-keyword: alter
  tenant:
    ignore-caller: com.dongxin.scm.sm.service.GetActualDeliveryService.addGetActualDelivery
#    table:
    table: cm_customer_visit_history,om_order,cm_customer_profile,cm_attorney,cm_customer_bank,cm_customer_address,cm_customer_credit,fm_credit,fm_invoice,fm_settle_info,fm_fund_pool,om_sales_order_det,om_sales_order,om_contract_provision,om_contract_det,om_contract,om_provision_base,om_provision,om_order_mat,om_order_det,sm_purchase_apply,sm_mat_reduce_record,sm_product,sm_stack_det,sm_stack,sm_stock,fm_fund_account,fm_refund_records,cm_salesman_info,sm_mat,sm_consignee,sm_inventory,fm_invoice_code,om_company_info,fm_invoice_detail,sm_processing,cm_customer_rate,sm_equipment_supplies,fm_acceptance_bank,sm_receiving,sm_warehouse_warrant,fm_financial_reconciliation,sm_material_summary,fm_finance_detail,sm_discharger_info,sm_shipper_info,fm_finance_mat_code,fm_finance_stock_balance,sm_inventory_timing,fm_fund_accountreceivable,sm_fleet,sm_import_stock_info,sm_shipping_management,sm_inventory_lock,fm_settle_inport,sm_average_cost,sm_inventory_allot,om_nomatdetail_contract,fm_fund_detail,sm_logistics_park_mat_basic_information,sm_get_actual_delivery,sm_get_actual_delivery_det,bd_unsettled,sm_good_entrustment_letter,sm_prepare_order,sm_shipping_management,fm_settle_import,sm_import_stock_info,sm_prepare_customer,fm_credit_adjust
#Mybatis输出sql日志
logging:
  level:
    org.jeecg.modules.system.mapper: debug
#cas单点登录
cas:
  prefixUrl: http://cas.example.org:8443/cas
#enable swagger
swagger:
  enable: false
data:
  update-record:
    tables: om_sales_order,om_sales_order_det,sm_stack,sm_stack_det,sm_inventory,fm_fund_pool
    enable: true
msg:
  appname: 'scm'
  white-list: '%'
  mq:
    enable: false
  local: AZX
  po:
    addr: http://10.200.16.136:50000/RESTAdapter
    auth:
      user: poq_azx
      pwd: Sap12345
    callback:
      addr: INTFLOG_BQ
#可信数据
trusted-third:
  key:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDj+bY+cSsqXRCaQAQ1J/0DtPTm
      1najdNbrB2LX8XCKshTexDbe2lXWAK9C90LIuJQT/CmfDWv/ggSRNFt1TzCiVa0s
      YVxZy8/utzWMqWxmdZQl5htnFADrFl+JGcaJDZM0Eeq8n0K6qvYbFNEYGZG5pY07
      TieeQ/WXjx8CM8Fj0wIDAQAB
    privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAOP5tj5xKypdEJpA
      BDUn/QO09ObWdqN01usHYtfxcIqyFN7ENt7aVdYAr0L3Qsi4lBP8KZ8Na/+CBJE0
      W3VPMKJVrSxhXFnLz+63NYypbGZ1lCXmG2cUAOsWX4kZxokNkzQR6ryfQrqq9hsU
      0RgZkbmljTtOJ55D9ZePHwIzwWPTAgMBAAECgYA+ia/erTjEJEd7qPf+hPu5Wpic
      AlUFPfX+/0W0Kz1OLs/e1EChHY/SZtmtKxsc6NVmLhRU11+69bW/B3fXVGPof7wU
      Ml1bOwJMhP01pu0eh3LxtXALzHTd0ak7yQ/bc60NSKFSVGxI4pHbHQn3ZjmEK0jP
      SKQC/wrRleH5ak510QJBAPXh2tjKoC1fOXTrozr3MGMLIBLAfAznlhBSa48Lhefo
      MJ24BWBQxBQxpfuNb0z83CuBBCaiEjtSkj0EDekviC8CQQDtWzmiEIU9iDXLww2v
      AmQAWDFdbRH67ciOc61UVxmJ2dHY+kGaCqLZBzBWR6swTYTdy+3/vwX3hf3SGOnr
      vFGdAkBaP+8q+Zy3aqdVQhRk1Uw+XlwEZgBiYDKVhRsToyAgUfpeOahHhP2jh+Gr
      pms+7+UEVtOmNoDIo3Mn0DAm8hpjAkBjmN/6LUx7oWhRdCuNwEcODfPI7DebP6Pk
      go280j+ZJJl1nq1gYg4rW2ThD3m57w1NtIDNy+5JCySSwHmHvaHRAkBfMHokUzje
      GMrHJa8p6uOfUygjra2+GUy5kkUEJDG0df5mhzwoTSdYDIjvtT+IvnfVwV2wWeCj
      PTnHkPjjkX+/
  client-name: supplier-chain
  api:
    pushApi: http://220.173.106.240:10062/test/api/sinatrue/sinatrueSignInfo/push
    viewApi: http://220.173.106.240:10062/test/api/sinatrue/sinatrueSignInfo/obtainFinalFile
    templateApi: http://220.173.106.240:10062/test/api/sinatrue/sinatrueSignInfo/obtainTemplateList

# 仓储系统对接
retrofit:
  anon:
    ip-white-list: 172.16.105.130
    token: 'sfkjjfesklfhf94eghjvsg'
wms:
  enable: true
  app-id: ed9b3bf7-e596-4a08-abbe-49723449dd3a # 用于与柳钢智慧物流云平台-仓储管理系统接口对接的appid(需注册)
  server-url: http://220.173.61.221:8236
  api:
    get-access-code: /SystemSettingService/GetAccessCode # 获取通行码
    get-product: /BaseDataService/GetProduct # 获取产品信息
    get-warehouse: /BaseDataService/GetWarehouse # 获取仓库信息
    get-inventory: /InventoryManagementService/GetInventory # 获取库存信息
    get-plate-no: /StockOutService/GetPlateNo # 获取车号
    get-address: /StockOutService/GetAddress # 获取目的地
    submit-bill-of-lading-plan: /StockOutService/SubmitBillOfLadingPlan # 发送提货计划
    revoke-bill-of-lading-plan: /StockOutService/RevokeBillOfLadingPlan # 撤销提货计划
    submit-transfer-ownership-plan: /TransferOwnershipService/SubmitTransferOwnershipPlan # 提交过户计划
    revoke-transfer-ownership-plan: /TransferOwnershipService/RevokeTransferOwnershipPlan # 撤销过户计划
  rsa:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqeQqQpd0PN6bNkKGKmqJI0vgh
      TyTrZnIyhCKhzkD4BbaYcmlntD/TVlNnpM6j9okBmKnTLic9YkIps4Uw3VC4JLvp
      dZCDBREloPqJqszDngG1Bg/G/GJ6Z1L52G3vA7s0oGctJZ8bXO6erjLMBbX9IYhz
      jZP+9ccom7cTe0gTUwIDAQAB
    private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKp5CpCl3Q83ps2Q
      oYqaokjS+CFPJOtmcjKEIqHOQPgFtphyaWe0P9NWU2ekzqP2iQGYqdMuJz1iQimz
      hTDdULgku+l1kIMFESWg+omqzMOeAbUGD8b8YnpnUvnYbe8DuzSgZy0lnxtc7p6u
      MswFtf0hiHONk/71xyibtxN7SBNTAgMBAAECgYEAnhCzoiGZEoYYjRyhHKJ6/SlY
      15HJ+tc35e0tK3jSNucdQsc7QuQYFj5CAaUH0XJD4Q4L0XtG+RzFmmMRiZh8QW1c
      e8kd4C/YT4lbqqaGEWC2B3W1SNwYcauZOCS0nXE7t4hWMSLzBvhabCIyJWgyCDg/
      MUhsqOT+/7oHAwflpAkCQQDi4I9HS6Q0g5VNdyI5Sk+ELKMAGIrTi58vlYKjqpE+
      ndrhA6hJUtypiebnFlMN5mthPxz+wubvic66gFMi1GKHAkEAwFr4a321Vze4zehE
      Z5Xbr71EbS9Z+v1uCLm/L8FQZAaGy4TCovpEpLfyyLcSYV+mZrHvkaCAfa6IoAAp
      Vm5f1QJAaTG73U/aRCsap/9sE+o7skpMDbhTbkDXv2VwXFiy3bitixV6Cv1rqQRy
      1oUIX3KOKVntJMbT8w8PlnP3mDenswJAQS0Ry2o2zaylw68VrnuKiot46f4HYRIJ
      /I7jhwzbbmj/t2nugUaHh8CEVRoi8jd0rItR/2gA4ZUH2h7z4sNXWQJAQq6K+j/W
      GgZNxZCqixroIrHAg6IwMLr6TsNmZ+AMtHRdR1YoGtIMd5kcdPGvnZ86aBoEaAN6
      0GM1lTpG05j76g==
